name: Build and Push

on:
  workflow_dispatch:

env:
  GHCR_NAMESPACE: mohammadshehadeh/lms

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo ${{ secrets.ACCESS_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build Image
        run: docker build -f apps/nextjs/Dockerfile -t ghcr.io/$GHCR_NAMESPACE/nextjs:latest .

      - name: Push Image
        run: docker push ghcr.io/$GHCR_NAMESPACE/nextjs:latest
